INSERT INTO `aircraft_models` (`wing_type`,`aircraft_model`,`manufacturer`,`IATACode`,`ICAOCode`,`type`) VALUES
    ('Fixed Wing', 'Airbus A350-1000', 'Airbus', '351', 'A35K', 'Airplane'),
    ('Fixed Wing', 'Antonov AN-124 Ruslan', 'Antonov', 'A4F', 'A124', 'Airplane'),
    ('Fixed Wing', 'Airbus A330-900neo', 'Airbus', '339', 'A339', 'Airplane'),
    ('Fixed Wing', 'Airbus A320neo', 'Airbus', '32N', 'A20N', 'Airplane'),
    ('Rotary Wing', 'Bell 212', 'Bell', 'BH2', 'B212', 'Helicopter'),
    ('Fixed Wing', 'Airbus A330-300', 'Airbus', '333', 'A333', 'Airplane'),
    ('Fixed Wing', 'Boeing 737-400', 'Boeing', '734', 'B734', 'Airplane'),
    ('Fixed Wing', 'Airbus A310', 'Airbus', '312', 'A310', 'Airplane'),
    ('Fixed Wing', 'Boeing 737-600', 'Boeing', '736', 'B736', 'Airplane'),
    ('Fixed Wing', 'Aerospatiale ATR 72', 'Aerospatiale', 'AT7', 'AT72', 'Airplane'),
    ('Fixed Wing', '8KCAB Decathlon, 8GCBC Scout', 'Aeroprakt', 'N/A', 'BL8', 'Airplane'),
    ('Fixed Wing', 'Aerospatiale ATR 42-500', 'Aerospatiale', 'AT5', 'AT45', 'Airplane'),
    ('Fixed Wing', 'BAe 146-300', 'British Aerospace', '143', 'B463', 'Airplane'),
    ('Fixed Wing', 'Aquila A 210', 'Aquila', 'N/A', 'A210', 'Airplane'),
    ('Fixed Wing', 'Antonov AN-32', 'Antonov', 'A32', 'AN32', 'Airplane'),
    ('Fixed Wing', '"Airbus A330-700 ""Beluga XL"""', 'Airbus', ';', 'A337', 'Airplane'),
    ('Fixed Wing', 'Avro RJ70', 'Avro International Aerospace', 'AR7', 'RJ70', 'Airplane'),
    ('Fixed Wing', 'Airbus A220-300', 'Airbus', '223', 'BCS3', 'Airplane'),
    ('Fixed Wing', 'Aerospatiale (Sud Aviation) Se.210 Caravelle', 'Aerospatiale', 'CRV', 'S210', 'Airplane'),
    ('Fixed Wing', 'Antonov An-158', 'Antonov', 'A58', 'A158', 'Airplane'),
    ('Fixed Wing', 'Aerospatiale ATR 72-600', 'Aerospatiale', 'ATR', 'AT76', 'Airplane'),
    ('Fixed Wing', 'Airbus A321', 'Airbus', '321', 'A321', 'Airplane'),
    ('Fixed Wing', 'Aerospatiale ATR 72-200 series', 'Aerospatiale', 'ATR', 'AT73', 'Airplane'),
    ('Fixed Wing', 'Airbus A340-600', 'Airbus', '346', 'A346', 'Airplane'),
    ('Fixed Wing', '"Airbus A300-600ST ""Super Transporter"" / ""Beluga"""', 'Airbus', 'ABB', 'A3ST', 'Airplane'),
    ('Fixed Wing', 'Beriev Be-200 Altair', 'Beriev Aircraft Company', 'N/A', 'BER2', 'Airplane'),
    ('Fixed Wing', 'Boeing 727-100', 'Boeing', '721', 'B721', 'Airplane'),
    ('Fixed Wing', 'Airbus A330-800neo', 'Airbus', '338', 'A338', 'Airplane'),
    ('Fixed Wing', 'Airbus A340-300', 'Airbus', '343', 'A343', 'Airplane'),
    ('Fixed Wing', 'Airbus A380-800', 'Airbus', '388', 'A388', 'Airplane'),
    ('Fixed Wing', 'Antonov An-148', 'Antonov', 'A81', 'A148', 'Airplane'),
    ('Fixed Wing', 'Antonov AN-26', 'Antonov', 'A26', 'AN26', 'Airplane'),
    ('Fixed Wing', 'Antonov AN-72 / AN-74', 'Antonov', 'AN7', 'AN72', 'Airplane'),
    ('Fixed Wing', 'Boeing 720B', 'Boeing', 'B72', 'B720', 'Airplane'),
    ('Rotary Wing', 'Bell 429', 'Bell', 'BH2', 'B429', 'Helicopter'),
    ('Fixed Wing', 'Avro RJ85', 'Avro International Aerospace', 'AR8', 'RJ85', 'Airplane'),
    ('Fixed Wing', 'BAe 146-200', 'British Aerospace', '142', 'B462', 'Airplane'),
    ('Fixed Wing', 'Airbus A340-200', 'Airbus', '342', 'A342', 'Airplane'),
    ('Rotary Wing', 'Bell 412', 'Bell', 'BH2', 'B412', 'Helicopter'),
    ('Fixed Wing', '7AC Champ, 7ECA Citabria', 'Champion Aircraft Corporation', 'N/A', 'CH7A', 'Airplane'),
    ('Fixed Wing', 'BAe 146-100', 'British Aerospace', '141', 'B461', 'Airplane'),
    ('Fixed Wing', 'Airbus A340-500', 'Airbus', '345', 'A345', 'Airplane'),
    ('Fixed Wing', 'Aeroprakt A-22 Foxbat / A-22 Valor / A-22 Vision', 'Aeroprakt', 'N/A', 'AP22', 'Airplane'),
    ('Fixed Wing', 'Boeing 727-200', 'Boeing', '722', 'B722', 'Airplane'),
    ('Fixed Wing', 'Beechcraft Baron / 58 Baron', 'Beechcraft', 'N/A', 'BE58', 'Airplane'),
    ('Fixed Wing', 'Airbus A350-900', 'Airbus', '359', 'A359', 'Airplane'),
    ('Fixed Wing', 'Aerospatiale SN.601 Corvette', 'Aerospatiale', 'NDC', 'S601', 'Airplane'),
    ('Fixed Wing', 'Boeing 747 LCF Dreamlifter', 'Boeing', '74B', 'BLCF', 'Airplane'),
    ('Fixed Wing', 'Airbus A300B2, A300B4, and A300C4', 'Airbus', 'AB4', 'A30B', 'Airplane'),
    ('Fixed Wing', 'Boeing 747-400', 'Boeing', '744', 'B744', 'Airplane'),
    ('Fixed Wing', 'Antonov AN-30', 'Antonov', 'A30', 'AN30', 'Airplane'),
    ('Fixed Wing', 'Boeing 737 MAX 9', 'Boeing', '7M9', 'B39M', 'Airplane'),
    ('Fixed Wing', 'Airbus A318', 'Airbus', '318', 'A318', 'Airplane'),
    ('Fixed Wing', 'Boeing 737-300', 'Boeing', '733', 'B733', 'Airplane'),
    ('Fixed Wing', 'Boeing 737 MAX 8', 'Boeing', '7M8', 'B38M', 'Airplane'),
    ('Fixed Wing', 'Boeing 717', 'Boeing', '717', 'B712', 'Airplane'),
    ('Fixed Wing', 'Airbus A319neo', 'Airbus', '31N', 'A19N', 'Airplane'),
    ('Fixed Wing', 'Boeing 737-700', 'Boeing', '73G', 'B737', 'Airplane'),
    ('Fixed Wing', 'Beechcraft Baron / 55 Baron', 'Beechcraft', 'N/A', 'BE55', 'Airplane'),
    ('Fixed Wing', 'Boeing 737-200', 'Boeing', '732', 'B732', 'Airplane'),
    ('Fixed Wing', 'Airbus A220-100', 'Airbus', '221', 'BCS1', 'Airplane'),
    ('Fixed Wing', 'Antonov AN-140', 'Antonov', 'A40', 'A140', 'Airplane'),
    ('Fixed Wing', 'Antonov AN-12', 'Antonov', 'ANF', 'AN12', 'Airplane'),
    ('Fixed Wing', 'Antonov AN-28', 'Antonov', 'A28', 'AN28', 'Airplane'),
    ('Fixed Wing', 'Boeing 747-100', 'Boeing', '741', 'B741', 'Airplane'),
    ('Fixed Wing', 'Aerospatiale ATR 72-500', 'Aerospatiale', 'ATR', 'AT75', 'Airplane'),
    ('Fixed Wing', 'Boeing 737 MAX 7', 'Boeing', '7M7', 'B37M', 'Airplane'),
    ('Fixed Wing', 'Aerospatiale (Nord) 262', 'Aerospatiale', 'ND2', 'N262', 'Airplane'),
    ('Fixed Wing', 'Aerospatiale ATR 42-300', 'Aerospatiale', 'AT4', 'AT43', 'Airplane'),
    ('Fixed Wing', 'Airbus A321neo', 'Airbus', '32Q', 'A21N', 'Airplane'),
    ('Fixed Wing', 'Airbus A330-200', 'Airbus', '332', 'A332', 'Airplane'),
    ('Fixed Wing', 'Boeing 707', 'Boeing', '703', 'B703', 'Airplane'),
    ('Fixed Wing', 'Boeing 737-900', 'Boeing', '739', 'B739', 'Airplane'),
    ('Fixed Wing', 'Boeing 737-800', 'Boeing', '738', 'B738', 'Airplane'),
    ('Fixed Wing', 'Beechcraft 1900', 'Beechcraft', 'BEH', 'B190', 'Airplane'),
    ('Fixed Wing', 'Avro RJ100', 'Avro International Aerospace', 'AR1', 'RJ1H', 'Airplane'),
    ('Fixed Wing', 'Airbus A320', 'Airbus', '320', 'A320', 'Airplane'),
    ('Fixed Wing', 'Boeing 737 MAX 10', 'Boeing', '7MJ', 'B3XM', 'Airplane'),
    ('Fixed Wing', 'Airbus A319', 'Airbus', '319', 'A319', 'Airplane'),
    ('Fixed Wing', '7GCAA, 7GCBC, 7KCAB Citabria', 'Champion Aircraft Corporation', 'N/A', 'CH7B', 'Airplane'),
    ('Fixed Wing', 'Airbus A300-600', 'Airbus', 'AB6', 'A306', 'Airplane'),
    ('Fixed Wing', 'Boeing 747-300', 'Boeing', '743', 'B743', 'Airplane'),
    ('Fixed Wing', 'Antonov An-225 Mriya', 'Antonov', 'A5F', 'A225', 'Airplane'),
    ('Fixed Wing', 'Boeing 737-500', 'Boeing', '735', 'B735', 'Airplane'),
    ('Fixed Wing', 'Boeing 747-200', 'Boeing', '742', 'B742', 'Airplane'),
    ('Fixed Wing', 'Aerospatiale/Alenia ATR 42-600', 'Aerospatiale', 'ATR', 'AT46', 'Airplane'),
    ('Fixed Wing', 'Antonov AN-24', 'Antonov', 'AN4', 'AN24', 'Airplane'),
    ('Fixed Wing', 'Boeing 747-400D', 'Boeing', '74J', 'B74D', 'Airplane'),
    ('Fixed Wing', 'Boeing 747-8', 'Boeing', '74H', 'B748', 'Airplane'),
    ('Fixed Wing', 'Boeing 767-300', 'Boeing', '763', 'B763', 'Airplane'),
    ('Fixed Wing', 'Boeing 777-200LR', 'Boeing', '77L', 'B77L', 'Airplane'),
    ('Fixed Wing', 'Boeing 757-200', 'Boeing', '752', 'B752', 'Airplane'),
    ('Fixed Wing', 'Boeing 777-300', 'Boeing', '773', 'B773', 'Airplane'),
    ('Fixed Wing', 'British Aerospace 125 series / Hawker/Raytheon 700/800/800XP/850/900', 'Hawker Beechcraft Corporation', 'H25', 'H25B', 'Airplane'),
    ('Fixed Wing', 'Bombardier 415', 'Bombardier', 'N/A', 'CL2T', 'Airplane'),
    ('Fixed Wing', 'Bombardier Global Express / Raytheon Sentinel', 'Bombardier', 'CCX', 'GLEX', 'Airplane'),
    ('Fixed Wing', 'Boeing 777-8', 'Boeing', '778', 'B778', 'Airplane'),
    ('Fixed Wing', 'Boeing 757-300', 'Boeing', '753', 'B753', 'Airplane'),
    ('Fixed Wing', 'Boeing 787-8', 'Boeing', '788', 'B788', 'Airplane'),
    ('Fixed Wing', 'Boeing 747SP', 'Boeing', '74L', 'B74S', 'Airplane'),
    ('Fixed Wing', 'Boeing 777-200 / Boeing 777-200ER', 'Boeing', '772', 'B772', 'Airplane'),
    ('Fixed Wing', 'Boeing 767-200', 'Boeing', '762', 'B762', 'Airplane'),
    ('Fixed Wing', 'Canadair Regional Jet 700', 'Bombardier', 'CR7', 'CRJ7', 'Airplane'),
    ('Fixed Wing', 'British Aerospace Jetstream 41', 'British Aerospace', 'J41', 'JS41', 'Airplane'),
    ('Fixed Wing', 'Boeing 767-400ER', 'Boeing', '764', 'B764', 'Airplane'),
    ('Fixed Wing', 'Bombardier BD-100 Challenger 300', 'Bombardier', 'N/A', 'CL30', 'Airplane'),
    ('Fixed Wing', 'Boeing 777-9', 'Boeing', '779', 'B779', 'Airplane'),
    ('Fixed Wing', 'British Aerospace 125-1000 series / Hawker/Raytheon 1000', 'Hawker Beechcraft Corporation', 'H25', 'H25C', 'Airplane'),
    ('Fixed Wing', 'Cessna 162', 'Cessna', 'CN1', 'C162', 'Airplane'),
    ('Fixed Wing', 'Boeing 787-10', 'Boeing', '781', 'B78X', 'Airplane'),
    ('Fixed Wing', 'Bombardier BD-700 Global 5000', 'Bombardier', 'CCX', 'GL5T', 'Airplane'),
    ('Fixed Wing', 'Canadair Regional Jet 1000', 'Bombardier', 'CRK', 'CRJX', 'Airplane'),
    ('Fixed Wing', 'Cessna Citation CJ3', 'Cessna', 'CNJ', 'C25B', 'Airplane'),
    ('Fixed Wing', 'British Aerospace Jetstream 31', 'British Aerospace', 'J31', 'JS31', 'Airplane'),
    ('Fixed Wing', 'British Aerospace ATP', 'British Aerospace', 'ATP', 'ATP', 'Airplane'),
    ('Fixed Wing', 'Canadair Regional Jet 900', 'Bombardier', 'CR9', 'CRJ9', 'Airplane'),
    ('Fixed Wing', 'Cessna 206 Stationair', 'Cessna', 'CN1', 'C206', 'Airplane'),
    ('Fixed Wing', 'Canadair Challenger', 'Bombardier', 'CCJ', 'CL60', 'Airplane'),
    ('Fixed Wing', 'CASA/IPTN CN-235', 'Indonesian Aerospace', 'CS5', 'CN35', 'Airplane'),
    ('Fixed Wing', 'De Havilland Canada DHC-5 Buffalo', 'De Havilland Aircraft of Canada', 'DHC', 'DHC5', 'Airplane'),
    ('Fixed Wing', 'Boeing 777-300ER', 'Boeing', '77W', 'B77W', 'Airplane'),
    ('Fixed Wing', 'Dassault Falcon 900', 'Dassault Falcon', 'DF9', 'F900', 'Airplane'),
    ('Fixed Wing', 'Cessna Citation III, VI, VII', 'Cessna', 'CNJ', 'C650', 'Airplane'),
    ('Fixed Wing', 'Cessna 177 Cardinal RG', 'Cessna', 'CN1', 'C77R', 'Airplane'),
    ('Fixed Wing', 'Cessna Citation CJ2', 'Cessna', 'CNJ', 'C25A', 'Airplane'),
    ('Fixed Wing', 'Cessna Citation Mustang', 'Cessna', 'CNJ', 'C510', 'Airplane'),
    ('Fixed Wing', 'Canadair Regional Jet 100', 'Bombardier', 'CR1', 'CRJ1', 'Airplane'),
    ('Fixed Wing', 'De Havilland DH.114 Heron', 'De Havilland Aircraft of Canada', 'DHH', 'HERN', 'Airplane'),
    ('Fixed Wing', 'British Aerospace Jetstream 32', 'British Aerospace', 'J32', 'JS32', 'Airplane'),
    ('Fixed Wing', 'Cirrus SF50 Vision Jet', 'Cirrus', ';', 'SF50', 'Airplane'),
    ('Fixed Wing', 'Cessna 172', 'Cessna', 'CN1', 'C172', 'Airplane'),
    ('Fixed Wing', 'Cessna Citation CJ4', 'Cessna', 'CNJ', 'C25C', 'Airplane'),
    ('Fixed Wing', 'Boeing 787-9', 'Boeing', '789', 'B789', 'Airplane'),
    ('Fixed Wing', 'Cessna CitationJet', 'Cessna', 'CNJ', 'C525', 'Airplane'),
    ('Fixed Wing', 'Cessna 310', 'Cessna', 'N/A', 'C310', 'Airplane'),
    ('Fixed Wing', 'De Havilland Canada DHC-6 Twin Otter', 'De Havilland Aircraft of Canada', 'DHT', 'DHC6', 'Airplane'),
    ('Fixed Wing', 'British Aerospace (BAC) One Eleven', 'British Aircraft Corporation', 'B11', 'BA11', 'Airplane'),
    ('Fixed Wing', 'Cessna 208 Caravan', 'Cessna', 'CN1', 'C208', 'Airplane'),
    ('Fixed Wing', 'De Havilland Canada DHC-8-300 Dash 8 / 8Q', 'De Havilland Aircraft of Canada', 'DH3', 'DH8C', 'Airplane'),
    ('Fixed Wing', 'De Havilland Canada DHC-2 Beaver', 'De Havilland Aircraft of Canada', 'DHP', 'DHC2', 'Airplane'),
    ('Fixed Wing', 'Curtiss C-46 Commando', 'Curtiss-Wright', 'CWC', 'C46', 'Airplane'),
    ('Fixed Wing', 'Cessna Citation I', 'Cessna', 'CNJ', 'C500', 'Airplane'),
    ('Fixed Wing', 'Canadair Regional Jet 200', 'Bombardier', 'CR2', 'CRJ2', 'Airplane'),
    ('Fixed Wing', 'Convair CV-580, Convair CV-600, Convair CV-640', 'Convair', 'CV5', 'CVLT', 'Airplane'),
    ('Fixed Wing', 'Cessna 152', 'Cessna', 'N/A', 'C152', 'Airplane'),
    ('Fixed Wing', 'Cessna 182 Skylane', 'Cessna', 'CN1', 'C182', 'Airplane'),
    ('Fixed Wing', 'CASA / IPTN 212 Aviocar', 'Indonesian Aerospace', 'CS2', 'C212', 'Airplane'),
    ('Fixed Wing', 'De Havilland Canada DHC-8-400 Dash 8Q', 'De Havilland Aircraft of Canada', 'DH4', 'DH8D', 'Airplane'),
    ('Fixed Wing', 'Douglas DC-8-50', 'McDonnell Douglas', 'D8T', 'DC85', 'Airplane'),
    ('Fixed Wing', 'Cessna Citation II', 'Cessna', 'CNJ', 'C550', 'Airplane'),
    ('Fixed Wing', 'Cessna 172 Cutlass RG', 'Cessna', 'CN1', 'C72R', 'Airplane'),
    ('Fixed Wing', 'Cessna Citation X', 'Cessna', 'CNJ', 'C750', 'Airplane'),
    ('Fixed Wing', 'Douglas DC-10', 'McDonnell Douglas', 'D1C', 'DC10', 'Airplane'),
    ('Fixed Wing', 'Diamond DA42', 'Diamond Aircraft Industries', 'N/A', 'DA42', 'Airplane'),
    ('Fixed Wing', 'Convair CV-240 & -440', 'Convair', 'CV4', 'CVLP', 'Airplane'),
    ('Fixed Wing', 'De Havilland Canada DHC-8-200 Dash 8 / 8Q', 'De Havilland Aircraft of Canada', 'DH2', 'DH8B', 'Airplane'),
    ('Fixed Wing', 'Cessna 210 Centurion', 'Cessna', 'CN1', 'C210', 'Airplane'),
    ('Fixed Wing', 'De Havilland Canada DHC-4 Caribou', 'De Havilland Aircraft of Canada', 'DHC', 'DHC4', 'Airplane'),
    ('Fixed Wing', 'Dassault Falcon 7X', 'Dassault Falcon', 'DF7', 'FA7X', 'Airplane'),
    ('Fixed Wing', 'Cessna Citation V', 'Cessna', 'CNJ', 'C560', 'Airplane'),
    ('Fixed Wing', 'Concorde', 'Aerospatiale', 'SSC', 'CONC', 'Airplane'),
    ('Fixed Wing', 'De Havilland DH.104 Dove', 'De Havilland Aircraft of Canada', 'DHD', 'DOVE', 'Airplane'),
    ('Fixed Wing', 'Douglas DC-6', 'McDonnell Douglas', 'D6F', 'DC6', 'Airplane'),
    ('Fixed Wing', 'Cessna Citation Excel', 'Cessna', 'CNJ', 'C56X', 'Airplane'),
    ('Fixed Wing', 'Cessna Citation Sovereign', 'Cessna', 'CNJ', 'C680', 'Airplane'),
    ('Fixed Wing', 'Dassault Falcon 50', 'Dassault Falcon', 'DF3', 'FA50', 'Airplane'),
    ('Fixed Wing', 'COMAC C919', 'China Commercial Aircraft', 'N/A', 'C919', 'Airplane'),
    ('Fixed Wing', 'De Havilland Canada DHC-3 Otter', 'De Havilland Aircraft of Canada', 'DHL', 'DHC3', 'Airplane'),
    ('Fixed Wing', 'De Havilland Canada DHC-8-100 Dash 8 / 8Q', 'De Havilland Aircraft of Canada', 'DH1', 'DH8A', 'Airplane'),
    ('Fixed Wing', 'De Havilland Canada DHC-2 Turbo-Beaver', 'De Havilland Aircraft of Canada', 'DHR', 'DH2T', 'Airplane'),
    ('Fixed Wing', 'Dassault Falcon 2000', 'Dassault Falcon', 'D20', 'F2TH', 'Airplane'),
    ('Fixed Wing', 'De Havilland Canada DHC-7 Dash 7', 'De Havilland Aircraft of Canada', 'DH7', 'DHC7', 'Airplane'),
    ('Fixed Wing', 'Douglas DC-3', 'McDonnell Douglas', 'D3F', 'DC3', 'Airplane'),
    ('Fixed Wing', 'Diamond DA62', 'Diamond Aircraft Industries', 'N/A', 'DA62', 'Airplane'),
    ('Fixed Wing', 'Douglas DC-9-10', 'McDonnell Douglas', 'D91', 'DC91', 'Airplane'),
    ('Fixed Wing', 'Douglas DC-8-72', 'McDonnell Douglas', 'D8Q', 'DC87', 'Airplane'),
    ('Fixed Wing', 'Douglas DC-9-50', 'McDonnell Douglas', 'D95', 'DC95', 'Airplane'),
    ('Fixed Wing', 'Embraer 175', 'Embraer', 'E75', 'E75S/L', 'Airplane'),
    ('Fixed Wing', 'Douglas DC-9-30', 'McDonnell Douglas', 'D93', 'DC93', 'Airplane'),
    ('Fixed Wing', 'Embraer 175 (long wing)', 'Embraer', 'E7W', 'E75L', 'Airplane'),
    ('Fixed Wing', 'Embraer Legacy 600 / Legacy 650', 'Embraer', 'ER3', 'E35L', 'Airplane'),
    ('Fixed Wing', 'Embraer EMB 120 Brasilia', 'Embraer', 'EM2', 'E120', 'Airplane'),
    ('Fixed Wing', 'Embraer 190', 'Embraer', 'E90', 'E190', 'Airplane'),
    ('Fixed Wing', 'Embraer E190-E2', 'Embraer', '290', 'E290', 'Airplane'),
    ('Fixed Wing', 'Embraer E195-E2', 'Embraer', '295', 'E295', 'Airplane'),
    ('Fixed Wing', 'Douglas DC-9-20', 'McDonnell Douglas', 'D92', 'DC92', 'Airplane'),
    ('Fixed Wing', 'Embraer Legacy 500 / Praetor 600', 'Embraer', 'N/A', 'E550', 'Airplane'),
    ('Rotary Wing', 'Eurocopter EC135 / EC635', 'Eurocopter', 'N/A', 'EC35', 'Helicopter'),
    ('Fixed Wing', 'Embraer RJ135', 'Embraer', 'ER3', 'E135', 'Airplane'),
    ('Fixed Wing', 'GippsAero GA8 Airvan', 'GippsAero', 'N/A', 'GA8', 'Airplane'),
    ('Fixed Wing', 'Douglas DC-9-40', 'McDonnell Douglas', 'D94', 'DC94', 'Airplane'),
    ('Fixed Wing', 'Fairchild Dornier 328JET', 'Dornier Luftfahrt', 'FRJ', 'J328', 'Airplane'),
    ('Rotary Wing', 'Eurocopter AS350 ï¿½ï¿½cureuil / AS355 Ecureuil 2 / AS550 Fennec', 'Eurocopter', 'NDE', 'AS50', 'Helicopter'),
    ('Rotary Wing', 'Eurocopter AS332 Super Puma', 'Eurocopter', 'APH', 'AS32', 'Helicopter'),
    ('Rotary Wing', 'Eurocopter (Aerospatiale) SA365C / SA365N Dauphin 2', 'Eurocopter', 'NDH', 'S65C', 'Helicopter'),
    ('Fixed Wing', 'Fokker F28 Fellowship', 'Fokker', 'F21', 'F28', 'Airplane'),
    ('Fixed Wing', 'Embraer Phenom 100', 'Embraer', 'EP1', 'E50P', 'Airplane'),
    ('Fixed Wing', 'Fokker 100', 'Fokker', '100', 'F100', 'Airplane'),
    ('Fixed Wing', 'Gulfstream G280', 'Gulfstream', 'GR3', 'G280', 'Airplane'),
    ('Fixed Wing', 'Douglas DC-8-62', 'McDonnell Douglas', 'D8L', 'DC86', 'Airplane'),
    ('Fixed Wing', 'Gulfstream Aerospace G-159 Gulfstream I', 'Gulfstream', 'GRS', 'G159', 'Airplane'),
    ('Fixed Wing', 'Fairchild Dornier Do.328', 'Dornier Luftfahrt', 'D38', 'D328', 'Airplane'),
    ('Fixed Wing', 'Embraer 170', 'Embraer', 'E70', 'E170', 'Airplane'),
    ('Fixed Wing', 'Fokker 70', 'Fokker', 'F70', 'F70', 'Airplane'),
    ('Fixed Wing', 'EV-97 EuroStar / EV-97 Harmony', 'Evektor-Aerotechnik', 'N/A', 'EV97', 'Airplane'),
    ('Rotary Wing', 'Eurocopter EC225 Super Puma', 'Eurocopter', 'N/A', 'EC25', 'Helicopter'),
    ('Fixed Wing', 'Grumman G-21 Goose', 'Grumman', 'GRG', 'G21', 'Airplane'),
    ('Fixed Wing', 'Embraer 195', 'Embraer', 'E95', 'E195', 'Airplane'),
    ('Fixed Wing', 'Embraer Phenom 300', 'Embraer', 'EP3', 'E55P', 'Airplane'),
    ('Fixed Wing', 'Gulfstream IV', 'Gulfstream', 'GJ4', 'GLF4', 'Airplane'),
    ('Fixed Wing', 'Hawker Siddeley HS 748', 'Avro International Aerospace', 'HS7', 'A748', 'Airplane'),
    ('Fixed Wing', 'Gulfstream/Rockwell (Aero) Turbo Commander', 'Gulfstream', 'ACT', 'AC90', 'Airplane'),
    ('Fixed Wing', 'Embraer Legacy 450 / Praetor 500', 'Embraer', 'N/A', 'E545', 'Airplane'),
    ('Fixed Wing', 'Gulfstream/Rockwell (Aero) Commander', 'Gulfstream', 'ACP', 'AC68', 'Airplane'),
    ('Fixed Wing', 'Embraer 175 (short wing)', 'Embraer', 'E7W', 'E75S', 'Airplane'),
    ('Fixed Wing', 'Ilyushin IL62', 'Ilyushin', 'IL6', 'IL62', 'Airplane'),
    ('Fixed Wing', 'Ilyushin IL114', 'Russian Aircraft Corporation MiG', 'I14', 'I114', 'Airplane'),
    ('Fixed Wing', 'Junkers Ju 52/3M', 'Junkers', 'JU5', 'JU52', 'Airplane'),
    ('Fixed Wing', 'Fokker F27 Friendship', 'Fokker', 'F27', 'F27', 'Airplane'),
    ('Rotary Wing', 'Eurocopter EC145', 'Eurocopter', 'N/A', 'EC45', 'Helicopter'),
    ('Fixed Wing', 'Fokker 50', 'Fokker', 'F50', 'F50', 'Airplane'),
    ('Fixed Wing', 'LET 410', 'Let Kunovice', 'L4T', 'L410', 'Airplane'),
    ('Fixed Wing', 'ICON A5', 'ICON', 'N/A', 'A5', 'Airplane'),
    ('Fixed Wing', 'Evektor SportStar', 'Evektor-Aerotechnik', 'N/A', 'EVSS', 'Airplane'),
    ('Fixed Wing', 'Lockheed L-1049 Super Constellation', 'Lockheed Corporation', 'L49', 'CONI', 'Airplane'),
    ('Fixed Wing', 'McDonnell Douglas MD-83', 'McDonnell Douglas', 'M83', 'MD83', 'Airplane'),
    ('Fixed Wing', 'Fairchild Dornier Do.228', 'Dornier Luftfahrt', 'D28', 'D228', 'Airplane'),
    ('Fixed Wing', 'Ilyushin IL96', 'Ilyushin', 'I93', 'IL96', 'Airplane'),
    ('Fixed Wing', 'McDonnell Douglas MD-11', 'McDonnell Douglas', 'M11', 'MD11', 'Airplane'),
    ('Fixed Wing', 'Embraer EMB 110 Bandeirante', 'Embraer', 'EMB', 'E110', 'Airplane'),
    ('Rotary Wing', 'Eurocopter (MBB) Bo.105', 'Eurocopter', 'MBH', 'B105', 'Helicopter'),
    ('Fixed Wing', 'Embraer RJ145', 'Embraer', 'ER4', 'E145', 'Airplane'),
    ('Rotary Wing', 'Eurocopter EC120 Colibri / Harbin HC120', 'Eurocopter', 'N/A', 'EC20', 'Helicopter'),
    ('Fixed Wing', 'Grumman G-73 Turbo Mallard', 'Grumman', 'GRM', 'G73T', 'Airplane'),
    ('Fixed Wing', 'Gulfstream V', 'Gulfstream', 'GJ5', 'GLF5', 'Airplane'),
    ('Fixed Wing', 'Harbin Yunshuji Y12', 'Harbin Aircraft Industry Group', 'YN2', 'Y12', 'Airplane'),
    ('Rotary Wing', 'Mil Mi-24 / Mi-25 / Mi-35', 'Mil Moscow Helicopter Plant', 'N/A', 'MI24', 'Helicopter'),
    ('Fixed Wing', 'Ilyushin IL86', 'Ilyushin', 'ILW', 'IL86', 'Airplane'),
    ('Fixed Wing', 'Gulfstream G650', 'Gulfstream', 'GJ6', 'GLF6', 'Airplane'),
    ('Fixed Wing', 'Government Aircraft Factories N22B / N24A Nomad', 'Government Aircraft Factories', 'CD2', 'NOMA', 'Airplane'),
    ('Fixed Wing', 'Ilyushin IL76', 'Ilyushin', 'IL7', 'IL76', 'Airplane'),
    ('Fixed Wing', 'Honda HA-420', 'Honda', 'N/A', 'HDJT', 'Airplane'),
    ('Fixed Wing', 'Mitsubishi Mu-2', 'Mitsubishi', 'MU2', 'MU2', 'Airplane'),
    ('Fixed Wing', 'Piper PA-28', 'Piper Aircraft', 'N/A', 'P28B', 'Airplane'),
    ('Fixed Wing', 'Israel Aircraft Industries 1124 Westwind', 'Israel Aircraft Industries', 'WWP', 'WW24', 'Airplane'),
    ('Fixed Wing', 'Lockheed L-182 / 282 / 382 (L-100) Hercules', 'Lockheed Corporation', 'LOH', 'C130', 'Airplane'),
    ('Fixed Wing', 'Piaggio P.180 Avanti', 'Piaggio Aero', 'N/A', 'P180', 'Airplane'),
    ('Fixed Wing', 'Ilyushin IL18', 'Ilyushin', 'IL8', 'IL18', 'Airplane'),
    ('Fixed Wing', 'Learjet 35 / 36 / C-21A', 'Learjet', 'LRJ', 'LJ35', 'Airplane'),
    ('Fixed Wing', 'McDonnell Douglas MD-88', 'McDonnell Douglas', 'M88', 'MD88', 'Airplane'),
    ('Fixed Wing', 'Learjet 60', 'Learjet', 'LRJ', 'LJ60', 'Airplane'),
    ('Fixed Wing', 'Pipistrel Sinus', 'Pipistrel', 'N/A', 'PISI', 'Airplane'),
    ('Fixed Wing', 'Lockheed L-1011 Tristar', 'Lockheed Corporation', 'L10', 'L101', 'Airplane'),
    ('Fixed Wing', 'Pilatus Britten-Norman BN-2A/B Islander', 'Britten-Norman', 'BNI', 'BN2P', 'Airplane'),
    ('Fixed Wing', 'Piper PA-31 Navajo', 'Piper Aircraft', 'PA2', 'PA31', 'Airplane'),
    ('Fixed Wing', 'McDonnell Douglas MD-87', 'McDonnell Douglas', 'M87', 'MD87', 'Airplane'),
    ('Fixed Wing', 'Lockheed L-188 Electra', 'Lockheed Corporation', 'LOE', 'L188', 'Airplane'),
    ('Fixed Wing', 'NAMC YS-11', 'Nihon Aircraft Manufacturing Corporation', 'YS1', 'YS11', 'Airplane'),
    ('Rotary Wing', 'MIL Mi-8 / Mi-17 / Mi-171 / Mil-172', 'Mil Moscow Helicopter Plant', 'MIH', 'MI8', 'Helicopter'),
    ('Fixed Wing', 'McDonnell Douglas MD-81', 'McDonnell Douglas', 'M81', 'MD81', 'Airplane'),
    ('Fixed Wing', 'Pilatus Britten-Norman BN-2A Mk III Trislander', 'Britten-Norman', 'BNT', 'TRIS', 'Airplane'),
    ('Fixed Wing', 'McDonnell Douglas MD-90', 'McDonnell Douglas', 'M90', 'MD90', 'Airplane'),
    ('Fixed Wing', 'Piper PA-44 Seminole', 'Piper Aircraft', 'N/A', 'PA44', 'Airplane'),
    ('Fixed Wing', 'McDonnell Douglas MD-82', 'McDonnell Douglas', 'M82', 'MD82', 'Airplane'),
    ('Fixed Wing', 'Pilatus PC-12', 'Pilatus Aircraft', 'PL2', 'PC12', 'Airplane'),
    ('Fixed Wing', 'Partenavia P.68', 'Vulcanair', 'PN6', 'P68', 'Airplane'),
    ('Rotary Wing', 'MD Helicopters MD900 Explorer', 'MD Helicopters', 'MD9', 'EXPL', 'Helicopter'),
    ('Fixed Wing', 'Piper PA-28', 'Piper Aircraft', 'N/A', 'P28A', 'Airplane'),
    ('Fixed Wing', 'Pilatus PC-6 Turbo Porter', 'Pilatus Aircraft', 'PL6', 'PC6T', 'Airplane'),
    ('Fixed Wing', 'Piper PA-46', 'Piper Aircraft', 'PAG', 'PA46', 'Airplane'),
    ('Fixed Wing', 'Shorts SC-5 Belfast', 'Short Brothers', 'SHB', 'BELF', 'Airplane'),
    ('Fixed Wing', 'Pipistrel Virus', 'Pipistrel', 'N/A', 'PIVI', 'Airplane'),
    ('Fixed Wing', 'Robin ATL', 'Avions Robin', 'ATL', 'ATL', 'Airplane'),
    ('Fixed Wing', 'Saab SF340A/B', 'Saab', 'SF3', 'SF34', 'Airplane'),
    ('Fixed Wing', 'Reims-Cessna F406 Caravan II', 'Cessna', 'CNT', 'F406', 'Airplane'),
    ('Fixed Wing', 'Shorts SC-7 Skyvan', 'Short Brothers', 'SHS', 'SC7', 'Airplane'),
    ('Fixed Wing', 'Pipistrel Taurus', 'Pipistrel', 'N/A', 'PITA', 'Airplane'),
    ('Fixed Wing', 'Tecnam P2002 Sierra', 'Tecnam', 'N/A', 'SIRA', 'Airplane'),
    ('Rotary Wing', 'Sikorsky S-58T', 'Sikorsky', 'S58', 'S58T', 'Helicopter'),
    ('Fixed Wing', 'Tupolev Tu-154', 'Tupolev', 'TU5', 'T154', 'Airplane'),
    ('Fixed Wing', 'Robin HR200/R2000 series, Alpha160A', 'Avions Robin', 'N/A', 'R200', 'Airplane'),
    ('Fixed Wing', 'Team Rocket F1', 'Team Rocket', 'N/A', 'TRF1', 'Airplane'),
    ('Rotary Wing', 'Sikorsky S-76', 'Sikorsky', 'S76', 'S76', 'Helicopter'),
    ('Fixed Wing', 'Tecnam P92 Echo / P92 Eaglet / P92 SeaSky', 'Tecnam', 'N/A', 'ECHO', 'Airplane'),
    ('Rotary Wing', 'Sikorsky S-61', 'Sikorsky', 'S61', 'S61', 'Helicopter'),
    ('Fixed Wing', 'Tecnam P2010', 'Tecnam', 'N/A', 'TWEN', 'Airplane'),
    ('Fixed Wing', 'Yakovlev Yak-42', 'Yakovlev', 'YK2', 'YK42', 'Airplane'),
    ('Fixed Wing', 'Sukhoi Superjet 100-95', 'Sukhoi', 'SU9', 'SU95', 'Airplane'),
    ('Fixed Wing', 'Tupolev Tu-134', 'Tupolev', 'TU3', 'T134', 'Airplane'),
    ('Fixed Wing', 'Tecnam P2012 Traveller', 'Tecnam', 'T12', 'P212', 'Airplane'),
    ('Fixed Wing', 'Saab 2000', 'Saab', 'S20', 'SB20', 'Airplane'),
    ('Fixed Wing', 'Tupolev Tu-144', 'Tupolev', 'N/A', 'T144', 'Airplane'),
    ('Fixed Wing', 'Shorts SD.330', 'Short Brothers', 'SH3', 'SH33', 'Airplane'),
    ('Fixed Wing', 'Shorts SD.360', 'Short Brothers', 'SH6', 'SH36', 'Airplane'),
    ('Rotary Wing', 'Sikorsky S-92', 'Sikorsky', 'S92', 'S92', 'Helicopter'),
    ('Fixed Wing', 'Socata TB-20 Trinidad', 'Socata', 'N/A', 'TB20', 'Airplane'),
    ('Fixed Wing', 'Tecnam P2006T', 'Tecnam', 'N/A', 'P06T', 'Airplane'),
    ('Fixed Wing', 'Tecnam P2008', 'Tecnam', 'N/A', 'P208', 'Airplane'),
    ('Fixed Wing', 'Tecnam P96', 'Tecnam', 'N/A', 'GOLF', 'Airplane'),
    ('Fixed Wing', 'Tupolev Tu-204 / Tu-214', 'Tupolev', 'T20', 'T204', 'Airplane'),
    ('Fixed Wing', 'TL Ultralight TL-96 Star / TL-2000 Sting', 'TL Ultralight', 'N/A', 'TL20', 'Airplane'),
    ('Fixed Wing', 'Yakovlev Yak-40', 'Yakovlev', 'YK4', 'YK40', 'Airplane');
